# NOTE: This docker-compose.yml is meant to be just an example guideline
# on how you can achieve the same. It is not intented to run out of the box
# and you must edit the below configurations to suit your needs.

version: "3.9"


services:
  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U listmonk"] # Check before starting the next service
      interval: 10s
      timeout: 5s
      retries: 6
    container_name: listmonk_db
    volumes: # to have a backup
      - "./pg:/var/lib/postgresql"

  app:
    restart: unless-stopped
    image: listmonk/listmonk:latest
    ports:
      - "9000:9000"
    environment:
      - TZ=Etc/UTC
    container_name: listmonk_app
    depends_on:
      - db
    volumes:
      - ./config.toml:/listmonk/config.toml


